// This file is auto-generated by Convex
// It will be regenerated when you run `npx convex dev`

export type DataModel = {
  quotations: {
    _id: string;
    _creationTime: number;
    projectId: string;
    customerId: string;
    status: "draft" | "awaiting_approval" | "approved" | "sent" | "accepted" | "rejected";
    createdAt: number;
    updatedAt: number;
    createdBy: string;
    owner: string;
    versions: any[];
    currentVersionId: string;
    approval?: any;
    sentAt?: number;
    decisionAt?: number;
    decisionReason?: string;
    contract?: any;
    sentInstructions: any[];
    project: any;
    customer: any;
    schedule: any;
    pricing: any;
    elements: any;
    products: any;
    documents: any;
    delivery: any;
    paymentSchedule: any;
    aiAnalysisInstruction?: any;
  };
  messages: {
    _id: string;
    _creationTime: number;
    quotationId: string;
    timestamp: number;
    author: string;
    text: string;
    type: "internal" | "customer";
  };
  communicationTasks: {
    _id: string;
    _creationTime: number;
    quotationId: string;
    type: "call" | "email" | "meeting" | "other";
    title: string;
    description?: string;
    dueDate?: number;
    completed: boolean;
    completedAt?: number;
    assignedTo: string;
    createdAt: number;
    notes?: string;
  };
  costEntries: {
    _id: string;
    _creationTime: number;
    quotationId: string;
    date: number;
    category: "elements" | "products" | "trusses" | "installation" | "logistics" | "design" | "other";
    description: string;
    amount: number;
    supplier?: string;
    costType: "material" | "labor";
    laborHours?: number;
    laborRate?: number;
  };
  files: {
    _id: string;
    _creationTime: number;
    quotationId: string;
    name: string;
    size: number;
    category: "Pääpiirustus" | "Rakennesuunnitelma" | "Sopimus" | "Asiakkaan Tiedosto" | "Muu Tiedosto";
    uploadedAt: number;
    uploader: string;
    storageId?: string;
  };
  pricingTemplates: {
    _id: string;
    _creationTime: number;
    name: string;
    categoryMarkups: any;
    commissionPercentage: number;
    vatMode: "standard" | "construction_service";
    isDefault: boolean;
    createdAt: number;
    updatedAt: number;
  };
};
