// This file is auto-generated by Convex
import type { DataModel } from "./api";
import type { PreloadedQuery, useQuery, useMutation, useAction } from "convex/react";

export type Preloaded<QueryName extends keyof Queries> = PreloadedQuery<Queries[QueryName]>;
export type UseQuery<QueryName extends keyof Queries> = ReturnType<typeof useQuery<Queries[QueryName]>>;
export type UseMutation<MutationName extends keyof Mutations> = ReturnType<typeof useMutation<Mutations[MutationName]>>;
export type UseAction<ActionName extends keyof Actions> = ReturnType<typeof useAction<Actions[ActionName]>>;

export type Queries = {};
export type Mutations = {};
export type Actions = {};
