// This file is auto-generated by Convex
import type { DataModel } from "./api";
import type { GenericQueryCtx, GenericMutationCtx, GenericActionCtx } from "convex/server";
import type { Query, Mutation, Action } from "./server";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export type Query<Args, Output> = Query<Args, Output>;
export type Mutation<Args, Output> = Mutation<Args, Output>;
export type Action<Args, Output> = Action<Args, Output>;
